### ISSUE TITLE
Модуль стоит ,но кнопки в кабинете не реагируют..

### ISSUE THREAD

**Issue by surikat1978** [mr-Evgen/balance_account#3]
Здравствуйте! С Рождеством Христовым!
Модуль установился нормально, включён в админке,но кнопки в кабинете "пополнить балланс" "мои счёта" и тд. не реагируют,то есть при нажатии ничего не происходит.
Стоит на 10.3 версии
В чём проблема. Подскажите?

**Comment by mr-Evgen** [comment]
В кодировке

7 января 2015 г., 23:02 пользователь surikat1978 <notifications@github.com>
написал:

**Comment by surikat1978** [comment]
в кодировке движка? у меня utf8 . а что это разве может быть проблемная кодировка. Я поставил ваш плагин buyvip и кодировка не сходилась в переводе . изменил все файлы в кодировку utf8 и плагин работает ,выполняет функцию перевода в вип.единственное, я пополнил счёт просто в ручную  админке для теста.Смотрел вроде ,не нашёл привязку модуля ballance к кодировке.
Это возможно как-то исправить?

**Comment by surikat1978** [comment]
там модуль вроде для utf 8  и  есть? как же можно добиться успеха с кнопками. в .htaccess что-то не так,где копать? заранее благодарю за ответ

**Comment by mr-Evgen** [comment]
Попробуйте пересохранить файлы модуля в нужной Вам кодировке.

8 января 2015 г., 18:55 пользователь surikat1978 <notifications@github.com>
написал:

**Comment by surikat1978** [comment]
я пробовал уже пересохранять все буквально файлы модуля. хотя большинство их и есть уже в utf. Модуль вообще тестировался на 10.3 ? я заметил ,что не только у меня такое, это частый трабл.

**Comment by mr-Evgen** [comment]
С github версией utf да. Проблемы бывают.

8 января 2015 г., 22:03 пользователь surikat1978 <notifications@github.com>
написал:

**Comment by surikat1978** [comment]
так я отсюда и скачал с github/  DLE 10.3 utf8 стоит оригинальная лицензия не активированная без сторонних модулей. только ваш установлен. шаблон default. более простых условий не представляю.

**Comment by surikat1978** [comment]
и опять на чистый движок  уже с cp 1251  также кнопки не фурычат.
вообще что-то не то здесь не рабочий мод

**Comment by mr-Evgen** [comment]
Ни у кого столько проблем не было как у Вас. Может проблема не в модуле.

9 января 2015 г., 22:20 пользователь surikat1978 <notifications@github.com>
написал:

**Comment by surikat1978** [comment]
Здравствуйте. Так где же у меня много проблем? github мало юзает русско-язычных,поэтому и отзывов нет практичеси.кнопки контроля модуля не функционируют и это вся проблема.
кривые руки ,если вы это имеете в виду здесь не причём. установлен профессионально. я не первый год уже пользуюсь этим движком. хостинг платный . уверен .что ошибка всё же в модуле. буду очень признателен ,если вы её исправите! установил всё по чистому dle 10.3 utf-8
http://valentynsmtvx.bitte16.in.ua
инклуд поставил в профиль

**Comment by mr-Evgen** [comment]
Страниа http://valentynsmtvx.bitte16.in.ua/engine/modules/balance_account/user/load_control.php

Должна выдавать Hacking attempt!

Попробуйте установить права на чтение для данного файла.

10 января 2015 г., 22:13 пользователь surikat1978
<notifications@github.com> написал:

**Comment by surikat1978** [comment]
сервер unix . ставил вначале 777 -без рузультата, потом 444 -также
как правильнее в моём случае?
я просматривал этот файл ещё вчера там где строчка charset и "  может где -то здесь кроется беда?

**Comment by surikat1978** [comment]
Спасибо. уже не требуется помощь. мне помогли хостеры как раз. там что-то не правильно именно с кодировкой файлов модуля. права совершенно не причём

**Comment by surikat1978** [comment]
ещё заметил в google chrome при нажатии пополнить страница оплаты отображается не правильно. в принципе не критично,но хотелось бы исправить.
Спасибо Большое за модуль!
